name: Rust

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [nightly]
    steps:
      - uses: hecrj/setup-rust-action@v1.0.2
        with:
          rust-version: ${{ matrix.rust }}
      - name: Install rustfmt
        run: rustup component add rustfmt
      - uses: actions/checkout@v1
      - name: Lint
        run: cargo fmt --all -- --check
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: hecrj/setup-rust-action@v1.0.2
        with:
          rust-version: nightly
      - name: Install clippy
        run: rustup component add clippy
      - uses: actions/checkout@v1
      - name: Lint
        run: cargo clippy --all-targets --all-features
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [nightly]
    needs: clippy
    steps:
      - uses: hecrj/setup-rust-action@v1.0.2
        with:
          rust-version: ${{ matrix.rust }}
      - uses: actions/checkout@v1
      - name: Build
        run: cargo build --verbose --all
      - name: Run tests
        run: cargo test --verbose --all
